AWSTemplateFormatVersion: 2010-09-09
Description: A CloudFormation template to create Elastic Search for TitleSearchMiddle.
Resources:
  randonlinkec2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds: ['sg-75793903']
      SubnetId: subnet-18409e7f
      Tags:
        - 
          Key: Name
          Value: randonlink
      ImageId: ami-013be31976ca2c322
      KeyName: deploy
  randonlinklistener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref randonlinktargetgroup
      LoadBalancerArn: !Ref randonlinkALB
      Port: 80
      Protocol: HTTP
  randonlinkALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: ['subnet-18409e7f','subnet-35476a0a']
      SecurityGroups: ['sg-75793903']
      Name: randonlink
  randonlinktargetgroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      UnhealthyThresholdCount: 3
      HealthCheckPath: /
      Name: MyTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: vpc-b3e66ac8
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
      Targets:
        - Id: !Ref randonlinkec2
          Port: 80
  randonlinkrecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt randonlinkALB.DNSName
        HostedZoneId: !GetAtt randonlinkALB.CanonicalHostedZoneID
      HostedZoneId: Z1P7IXC8UCSOZR
      Comment: 'DNS name for my instance.'
      Name: 'randon.link'
      Type: A
